apiVersion: v1
kind: Service
metadata:
  name: ylz-xyz-file-svc
  labels:
    name: ylz-xyz-file-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: ylz-xyz-file-svc